const cardData = [
  {
    id: 1,
    title: "In Me Mum's Car",
    name: "Sally Speedracer",
    description:
      "An absolute all time video. She really went Broom Broom and her mom had her get out the car. That's crazy.",
    src: "/assets/gifs/mumsCar.gif",
    link: "https://youtu.be/LWVTsHNQIiU",
    embedLink: "https://www.youtube.com/embed/LWVTsHNQIiU",
    upvoteCount: 0,
    downvoteCount: 0,
  },
  {
    id: 2,
    title: "Chris, Is That a Weed?",
    name: "Chris Jones",
    description:
      "A hectic video from the jump, but one that inpired millions of youth. Was it a weed? We're all still searching for the answer..",
    src: "/assets/gifs/weed.gif",
    link: "https://youtu.be/g6cIYDvFS-U",
    embedLink: "https://www.youtube.com/embed/g6cIYDvFS-U",
    upvoteCount: 0,
    downvoteCount: 0,
  },
  {
    id: 3,
    title: "This Bitch Empty",
    name: "Emptyana Jones",
    description:
      "Probably the first time we ever heard the word 'Yeet'. Changed the course of history, forever.",
    src: "/assets/gifs/empty.gif",
    link: "https://youtu.be/2Bjy5YQ5xPc",
    embedLink: "https://www.youtube.com/embed/2Bjy5YQ5xPc",
    upvoteCount: 0,
    downvoteCount: 0,
  },
  {
    id: 4,
    title: "They Were Roommates",
    name: "Sidewalk Sarah",
    description:
      "The first time the whole world eavesdropped on conversation together. They were roommates, but what did they do? ",
    src: "/assets/gifs/theyWereRoomates.gif",
    link: "https://youtu.be/y-P0m0M_8pc",
    embedLink: "https://www.youtube.com/embed/y-P0m0M_8pc",
    upvoteCount: 0,
    downvoteCount: 0,
  },
  {
    id: 5,
    title: "LeBron James",
    name: "Lil Timmy",
    description:
      "This kid was a bigger star at the age of 9 than most of us could ever dream of. Just a kid who loves LeBron James.",
    src: "/assets/gifs/lebronjames.gif",
    link: "https://youtu.be/ZeIr0FVJwGs",
    embedLink: "https://www.youtube.com/embed/ZeIr0FVJwGs",
    upvoteCount: 0,
    downvoteCount: 0,
  },
  {
    id: 6,
    title: "Look At All Those Chickens",
    name: "Gabby Goose",
    description:
      "This little legend is the reason we can't see a chicken without thinking or saying the punchline of this video.",
    src: "/assets/gifs/chickens.gif",
    link: "https://youtu.be/RUTyw9tIc-M",
    embedLink: "https://www.youtube.com/embed/RUTyw9tIc-M",
    upvoteCount: 0,
    downvoteCount: 0,
  },
  {
    id: 7,
    title: "I Could Have Dropped My Croissant!",
    name: "Pastry Patrick",
    description:
      "SMDH. You should know better than to get between a man and his pastry. This man doesn't play around.",
    src: "/assets/gifs/croissant.gif",
    link: "https://youtu.be/ZzWqfJFxC0w",
    embedLink: "https://www.youtube.com/embed/ZzWqfJFxC0w",
    upvoteCount: 0,
    downvoteCount: 0,
  },
  {
    id: 8,
    title: "Back At It Again At Krispy Kreme",
    name: "Donnie Donut",
    description:
      "This guy was destined to be a star. Sheer athleticism mixed with the bravery to do a backflip in a Krispy Kreme. Say less.",
    src: "/assets/gifs/krispyKreme.gif",
    link: "https://youtu.be/ax27VgI-lVE",
    embedLink: "https://www.youtube.com/embed/ax27VgI-lVE",
    upvoteCount: 0,
    downvoteCount: 0,
  },
  {
    id: 9,
    title: "What's 9 + 10?",
    name: "Math Whiz Manny",
    description: `This kid single handedly made all schools remove 9 + 10 from any curriculum. Our generation's Isaac Newton.`,
    src: "/assets/gifs/ninePlusTen.gif",
    link: "https://youtu.be/BzVXbeASRiQ",
    embedLink: "https://www.youtube.com/embed/BzVXbeASRiQ",
    upvoteCount: 0,
    downvoteCount: 0,
  },
  {
    id: 10,
    title: "Tre's Got a Basketball Game Tomorrow",
    name: "Tre",
    description:
      "Tre posted this Vine and his basketball game the next day had more attendees than the Super Bowl. True story.",
    src: "/assets/gifs/tre.gif",
    link: "https://youtu.be/j5bRtIfPlyA",
    embedLink: "https://www.youtube.com/embed/j5bRtIfPlyA",
    upvoteCount: 0,
    downvoteCount: 0,
  },
  {
    id: 11,
    title: "Hi, Welcome To Chili's",
    name: "Charlie Chili",
    description:
      "Iconic, legendary, talented, revolutionary. Chili's owes this man everything for their success.",
    src: "/assets/gifs/chilis.gif",
    link: "https://youtu.be/WEGCAS8nCPU",
    embedLink: "https://www.youtube.com/embed/WEGCAS8nCPU",
    upvoteCount: 0,
    downvoteCount: 0,
  },
  {
    id: 12,
    title: "I SMELL LIKE BEEF",
    name: "The Beef Baby",
    description:
      "If this baby doesn't have star potential then no one does. She smells like beef and we're all ok w that. Prolly kobe beef too.",
    src: "/assets/gifs/beef.gif",
    link: "https://youtu.be/W-lrxHS9vZ4",
    embedLink: "https://www.youtube.com/embed/W-lrxHS9vZ4",
    upvoteCount: 0,
    downvoteCount: 0,
  },
  {
    id: 13,
    title: "Two Bros Chillin In The Hot Tub",
    name: "Anthony Padilla",
    description:
      "A stunning 5 second documentary on 2 bros enjoying each others company, but at a distance that is very bro friendly.",
    src: "/assets/gifs/hotTub.gif",
    link: "https://youtu.be/EwAajOtfNT8",
    embedLink: "https://www.youtube.com/embed/EwAajOtfNT8",
    upvoteCount: 0,
    downvoteCount: 0,
  },
  {
    id: 14,
    title: "Country Boy, I Love Youuuuu",
    name: "Country Gal",
    description:
      "She was a kid when she made this video, imagine how she's evolved. Also did the country boy love her back?",
    src: "/assets/gifs/countryBoy.gif",
    link: "https://youtu.be/oz5cROtMKcM",
    embedLink: "https://www.youtube.com/embed/oz5cROtMKcM",
    upvoteCount: 0,
    downvoteCount: 0,
  },
  {
    id: 15,
    title: "Need For Speed",
    name: "Chloe Lmao",
    description:
      "This girl had the swag to carry an entire generation. She's also the inspiration for Morphius' glasses in The Matrix.",
    src: "/assets/gifs/speed.gif",
    link: "https://youtu.be/Wlyq22ybsRw",
    embedLink: "https://www.youtube.com/embed/Wlyq22ybsRw",
    upvoteCount: 0,
    downvoteCount: 0,
  },
];

export default cardData;
